pipeline {
    agent {
       docker {
          image "python:3.5.1"
        }
    }
    stages {
        stage("Install dependencies") {
            steps {
                sh "pip install -r requirements.txt"
            }
        }
        stage("Run tests") {
            steps {
                sh "robot -d ./logs -i smoke tests"
            }
        }
        post {
            always {
                robot "logs"
            }
        }
    }
}